[profile.default]
auto_detect_solc = false
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "ipfs"
cbor_metadata = true
revert-strings = "default"
create2_deployer = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
always_use_create_2_factory = true
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
bitsy    = "https://rpc.bitsy.network"
1        = "https://ethereum-rpc.publicnode.com"            # Ethereum Mainnet
11155111 = "https://ethereum-sepolia-rpc.publicnode.com"    # Ethereum Sepolia
42161    = "https://arbitrum-one-rpc.publicnode.com"        # Arbitrum Mainnet
421614   = "https://arbitrum-sepolia-rpc.publicnode.com"    # Arbitrum Sepolia
8453     = "https://base-rpc.publicnode.com"                # Base Mainnet
84532    = "https://base-sepolia-rpc.publicnode.com"        # Base Sepolia
56       = "https://bsc-rpc.publicnode.com"                 # BNB Mainnet
97       = "https://bsc-testnet-rpc.publicnode.com"         # BNB Testnet
137      = "https://polygon-rpc.publicnode.com"             # Polygon Mainnet
80002    = "https://polygon-amoy-rpc.publicnode.com"        # Polygon Amoy
10       = "https://optimism-rpc.publicnode.com"            # Optimism Mainnet
11155420 = "https://optimism-sepolia-rpc.publicnode.com"    # Optimism Sepolia

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
